.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. babocoin_qt test_babocoin_qt
clean: FORCE
	$(MAKE) -C .. babocoin_qt_clean test_babocoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_babocoin_qt_check
babocoin-qt babocoin-qt.exe: FORCE
	 $(MAKE) -C .. babocoin_qt
